server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:h2_memory_db
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /momentum-active-shoppe/swagger-ui.html

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: MomentumActiveShoppeApplication
